version: '3.8'

services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.12.1
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
    ports:
      - 9200:9200
    networks:
      - elk
    volumes:
      - es-data:/usr/share/elasticsearch/data

  fluentd:
    image: fluent/fluentd:v1.12-1
    container_name: fluentd
    restart: always
    volumes:
      - ./fluentd/conf:/fluentd/etc
      - fluentd-data:/fluentd/log
    environment:
      - FLUENTD_CONF=logstash.conf
    networks:
      - elk

  kibana:
    image: docker.elastic.co/kibana/kibana:7.12.1
    container_name: kibana
    ports:
      - 5601:5601
    depends_on:
      - elasticsearch
    networks:
      - elk

  fs-app1:
    build: .
    container_name: fs-app1
    logging:
      driver: "fluentd"
      options:
        fluentd-address: "fluentd:24224"
        tag: "docker.{{.Name}}"
    depends_on:
      - fluentd
    networks:
      - elk

networks:
  elk:
    driver: bridge

volumes:
  es-data:
  fluentd-data: